name: cddd-env-prefer-light

channels:
  - rdkit
  - defaults

dependencies:
  - python==3.7.7
  - numpy
  - rdkit==2020.09.1.0
  - scikit-learn==0.24.1
  - tensorflow-gpu==1.13.1
  - pip:
      - dirhash
      - pandas
      - pyyaml
      - matplotlib
      - seaborn