name: moler-env-prefer-light
channels:
  - rdkit
  - defaults
  - plotly
  - pytorch
  - conda-forge
dependencies:
  - pip<22
  - python==3.7.7
  - matplotlib
  - numpy==1.21.5
  - rdkit==2020.09.1.0
  - scikit-learn==0.24.1
  - seaborn
  - tqdm
  - tensorflow==2.9.1
  - pip:
    - pandas>=1.2.4
    - tf2-gnn~=2.12.0
    - pyyaml
    - dirhash
    - matplotlib-inline==0.1.3
    - ipywidgets
    - more-itertools