experiment_name: small_data_32
id_column_name: Assay_ID
limit_def: 32
path_to_df: pat_to/FS-mol_data/fs-mol/csv_files/CHEMBL1738502.csv
problem_type: classification
properties_column_name_list:
- Property
smiles_column_name: SMILES
splitting_strategy: random
