experiment_name: small_data_64
id_column_name: Assay_ID
limit_def: 64
path_to_df: path_to/FS-mol_data/fs-mol/csv_files/CHEMBL915809.csv
problem_type: classification
properties_column_name_list:
- Property
smiles_column_name: SMILES
splitting_strategy: random
