experiment_name: small_data
id_column_name: Assay_ID
limit_def: 0
path_to_df: none
problem_type: classification
properties_column_name_list:
- Property
smiles_column_name: SMILES
splitting_strategy: random
