experiment_name: small_data_128
id_column_name: Assay_ID
limit_def: 128
path_to_df: path_to/FS-mol_data/fs-mol/csv_files/CHEMBL1737951.csv
problem_type: classification
properties_column_name_list:
- Property
smiles_column_name: SMILES
splitting_strategy: random
